# Generated by Django 5.1.2 on 2024-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_chat', '0009_alter_chatmessage_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
