# Generated by Django 5.1.2 on 2024-10-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_chat', '0010_remove_chatmessage_group_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holy_chat.group'),
        ),
    ]
