# Generated by Django 5.1.2 on 2024-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_chat', '0012_chatmessage_file_alter_chatmessage_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
