# Generated by Django 5.1.2 on 2024-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy_chat', '0013_remove_chatmessage_file_chatmessage_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
